"""add equipment and image_url to exercises

Revision ID: 18134ff9d637
Revises: bf5760fb3992
Create Date: 2026-03-27 12:18:31.346577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18134ff9d637'
down_revision = 'bf5760fb3992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseTemplates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_exercise_name_equipment', ['name', 'equipment'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerciseTemplates', schema=None) as batch_op:
        batch_op.drop_constraint('uq_exercise_name_equipment', type_='unique')
        batch_op.drop_column('image_url')
        batch_op.drop_column('equipment')

    # ### end Alembic commands ###
