"""add order to exercises and sets, add bodyweight_logs and personal_records

Revision ID: 5c082c82a6b0
Revises: 80e280607884
Create Date: 2026-04-15 13:15:58.717788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c082c82a6b0'
down_revision = '80e280607884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodyweight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_template_id', sa.Integer(), nullable=False),
    sa.Column('pr_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_template_id'], ['exerciseTemplates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_template_id', 'pr_type', name='uq_pr_user_exercise_type')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('order')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('order')

    op.drop_table('personal_records')
    op.drop_table('bodyweight_logs')
    # ### end Alembic commands ###
