"""add notes to exercise

Revision ID: 6625b7742226
Revises: g5h6i7j8k9l0
Create Date: 2026-05-20 15:30:19.444925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6625b7742226'
down_revision = 'g5h6i7j8k9l0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_muscle_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_muscle_exercise_id'))
        batch_op.create_index(batch_op.f('ix_exercise_muscle_mappings_exercise_template_id'), ['exercise_template_id'], unique=False)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('notes')

    with op.batch_alter_table('exercise_muscle_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_muscle_mappings_exercise_template_id'))
        batch_op.create_index(batch_op.f('ix_exercise_muscle_exercise_id'), ['exercise_template_id'], unique=False)

    # ### end Alembic commands ###
