"""add elevation_gain to sets

Revision ID: 7c31ec05b69d
Revises: h6i7j8k9l0m1
Create Date: 2026-06-03 10:53:05.790632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c31ec05b69d'
down_revision = 'h6i7j8k9l0m1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elevation_gain', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_column('elevation_gain')

    # ### end Alembic commands ###
