"""add exercise_template_id fk to exercises and fk to active_routine_id

Revision ID: 80e280607884
Revises: 18134ff9d637
Create Date: 2026-04-15 13:07:19.960387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e280607884'
down_revision = '18134ff9d637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_exercises_exercise_template_id', 'exerciseTemplates', ['exercise_template_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_active_routine_id', 'routines', ['active_routine_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exercise_template_id')

    # ### end Alembic commands ###
