"""Add set_type to sets

Revision ID: af3f1dfc30e9
Revises: 5c082c82a6b0
Create Date: 2026-04-29 12:16:41.335417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3f1dfc30e9'
down_revision = '5c082c82a6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_type', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_column('set_type')

    # ### end Alembic commands ###
