"""add active_routine_id to user

Revision ID: bf5760fb3992
Revises: 
Create Date: 2026-03-27 12:05:53.739291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5760fb3992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    existing_tables = conn.dialect.get_table_names(conn)
    if 'users' in existing_tables:
        op.drop_table('users')
    if 'routine_ex' in existing_tables:
        op.drop_table('routine_ex')
    if 'routines' in existing_tables:
        with op.batch_alter_table('routines', schema=None) as batch_op:
            batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
    if 'user' in existing_tables:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('active_routine_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active_routine_id')

    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_column('description')

    op.create_table('routine_ex',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('routine_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_template_id', sa.INTEGER(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_template_id'], ['exerciseTemplates.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), nullable=False),
    sa.Column('username', sa.VARCHAR(length=250), nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
